[package]
name = "aoc"
version = "0.1.0"
authors = ["Mischa Spiegelmock <me@mish.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
debug = true
